-- ============================================================================
-- ALTITUDE V32 — auditoria de redefinição de senha
-- Não armazena senhas. As alterações de senha são executadas exclusivamente
-- por Edge Functions com SUPABASE_SERVICE_ROLE_KEY.
-- ============================================================================

create table if not exists public.auditoria_redefinicoes_senha (
  id bigint generated by default as identity primary key,
  aluno_id uuid,
  aluno_email text,
  redefinido_por uuid,
  origem text not null default 'PORTAL_GESTAO',
  criado_em timestamptz not null default now()
);

create index if not exists idx_auditoria_redef_senha_aluno
  on public.auditoria_redefinicoes_senha (aluno_id, criado_em desc);

alter table public.auditoria_redefinicoes_senha enable row level security;
revoke all on public.auditoria_redefinicoes_senha from anon, authenticated;

create table if not exists public.solicitacoes_redefinicao_senha (
  id bigint generated by default as identity primary key,
  aluno_id uuid,
  email text not null,
  origem text not null default 'PORTAL_PUBLICO',
  criado_em timestamptz not null default now()
);

create index if not exists idx_solicitacoes_redef_senha_email
  on public.solicitacoes_redefinicao_senha (email, criado_em desc);

alter table public.solicitacoes_redefinicao_senha enable row level security;
revoke all on public.solicitacoes_redefinicao_senha from anon, authenticated;

comment on table public.auditoria_redefinicoes_senha is
  'Auditoria de redefinições feitas pela gestão. Nunca armazena a senha.';
comment on table public.solicitacoes_redefinicao_senha is
  'Controle de frequência para solicitações públicas de recuperação de senha.';
