-- ============================================================================
-- ALTITUDE V36
-- Fluxo acadêmico: avaliação -> certificado, teto de 200h e agenda automática
-- ============================================================================

begin;

-- 0) Catálogo persistente de áreas de curso para a gestão.
create table if not exists public.areas_cursos_v36 (
  id bigint generated by default as identity primary key,
  nome text not null,
  slug text not null unique,
  ativo boolean not null default true,
  criado_por uuid null,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

alter table public.areas_cursos_v36 enable row level security;
drop policy if exists gestor_le_areas_cursos_v36 on public.areas_cursos_v36;
create policy gestor_le_areas_cursos_v36 on public.areas_cursos_v36
for select to authenticated using (public.e_gestor(2));
drop policy if exists gestor_gerencia_areas_cursos_v36 on public.areas_cursos_v36;
create policy gestor_gerencia_areas_cursos_v36 on public.areas_cursos_v36
for all to authenticated using (public.e_gestor(2)) with check (public.e_gestor(2));

insert into public.areas_cursos_v36(nome,slug) values
  ('Tecnologia','tecnologia'),('Humanas','humanas'),('Saúde','saude'),('Administração','administracao'),('Engenharia','engenharia')
on conflict(slug) do nothing;

-- 1) Proteção de novas solicitações de certificado.
--    Registros históricos acima de 200h continuam consultáveis; o bloqueio atua
--    em novas inclusões ou quando a carga for alterada.
create or replace function public.validar_certificado_v36()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
declare
  v_horas_solicitadas integer:=coalesce(new.horas_solicitadas,0);
  v_horas_emitidas integer:=coalesce(new.horas_emitidas,0);
begin
  if tg_op='INSERT' then
    if v_horas_solicitadas>200 or v_horas_emitidas>200 then
      raise exception 'Cada certificado pode ter no máximo 200 horas';
    end if;
    if v_horas_solicitadas<0 or v_horas_emitidas<0 then
      raise exception 'A carga horária do certificado não pode ser negativa';
    end if;
  elsif new.horas_solicitadas is distinct from old.horas_solicitadas
     or new.horas_emitidas is distinct from old.horas_emitidas then
    if v_horas_solicitadas>200 or v_horas_emitidas>200 then
      raise exception 'Cada certificado pode ter no máximo 200 horas';
    end if;
    if v_horas_solicitadas<0 or v_horas_emitidas<0 then
      raise exception 'A carga horária do certificado não pode ser negativa';
    end if;
  end if;

  if tg_op='INSERT' and new.aluno_id is not null and new.curso_id is not null then
    if not exists(
      select 1
      from public.avaliacoes_cursos av
      where av.aluno_id=new.aluno_id and av.curso_id=new.curso_id
    ) then
      raise exception 'Avalie o curso antes de solicitar o certificado';
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists trg_validar_certificado_v36 on public.certificados;
create trigger trg_validar_certificado_v36
before insert or update
on public.certificados
for each row execute function public.validar_certificado_v36();

-- 2) Recalcula de uma vez todas as agendas profissionais pendentes.
--    A função V34.3 já usa uma linha temporal global de 8h/dia por aluno:
--    se o certificado anterior terminou com horas livres no último dia, o
--    certificado seguinte reutiliza esse saldo antes de avançar para outro dia.
create or replace function public.gestor_recalcular_previsoes_todos_v36()
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  r record;
  v_total integer:=0;
begin
  if auth.uid() is null or not public.e_gestor(2) then
    raise exception 'Acesso restrito à gestão acadêmica';
  end if;

  for r in
    select distinct c.aluno_id
    from public.certificados c
    join public.cursos cu on cu.id=c.curso_id
    where c.aluno_id is not null
      and upper(coalesce(cu.tipo_curso,c.tipo_curso_snapshot,'PROFISSIONAL'))='PROFISSIONAL'
      and upper(coalesce(c.status,'')) not in ('CANCELADO','BLOQUEADO')
  loop
    perform public.recalcular_previsoes_profissionais_v34_3(r.aluno_id);
    v_total:=v_total+1;
  end loop;

  return jsonb_build_object(
    'ok',true,
    'alunos_processados',v_total,
    'limite_diario',8,
    'maximo_por_certificado',200,
    'mensagem','Períodos recalculados sem lacunas e sem sobreposição.'
  );
end;
$$;

revoke all on function public.gestor_recalcular_previsoes_todos_v36() from public;
grant execute on function public.gestor_recalcular_previsoes_todos_v36() to authenticated;

-- 3) Feed explicativo para o gestor. Não cria lançamentos duplicados; apenas
--    descreve a agenda já calculada em certificados.
create or replace function public.gestor_notificacoes_horas_v36()
returns table(
  certificado_id bigint,
  aluno_id uuid,
  aluno_nome text,
  aluno_ra text,
  curso_nome text,
  horas integer,
  periodo_inicio date,
  periodo_fim date,
  horas_comprometidas_anteriores integer,
  saldo_reaproveitado_no_dia integer,
  mensagem text
)
language sql
stable
security definer
set search_path=public
as $$
  with base as (
    select
      c.id certificado_id,
      c.aluno_id,
      coalesce(c.nome_aluno,a.nome,'Aluno') aluno_nome,
      a.ra aluno_ra,
      coalesce(c.nome_curso,cu.titulo,'Curso') curso_nome,
      coalesce(nullif(c.horas_emitidas,0),c.horas_solicitadas,0)::integer horas,
      coalesce(c.data_inicio_prevista,c.periodo_inicio) periodo_inicio,
      coalesce(c.data_final_prevista,c.periodo_fim) periodo_fim,
      coalesce(c.horas_comprometidas_anteriores,0)::integer comprometidas,
      case
        when coalesce(c.horas_comprometidas_anteriores,0)<=0 then 0
        when mod(coalesce(c.horas_comprometidas_anteriores,0),8)=0 then 0
        else 8-mod(coalesce(c.horas_comprometidas_anteriores,0),8)
      end::integer saldo_dia
    from public.certificados c
    join public.cursos cu on cu.id=c.curso_id
    left join public.alunos a on a.user_id=c.aluno_id
    where upper(coalesce(cu.tipo_curso,c.tipo_curso_snapshot,'PROFISSIONAL'))='PROFISSIONAL'
      and upper(coalesce(c.status,'')) in ('PENDENTE','AGUARDANDO_HORAS','AUTORIZADO_AGUARDANDO_DATA')
  )
  select
    b.certificado_id,b.aluno_id,b.aluno_nome,b.aluno_ra,b.curso_nome,b.horas,
    b.periodo_inicio,b.periodo_fim,b.comprometidas,b.saldo_dia,
    case
      when b.comprometidas=0 then
        format('Primeiro período do aluno: %s a %s, calculado no limite de 8h por dia.',
          to_char(b.periodo_inicio,'DD/MM/YYYY'),to_char(b.periodo_fim,'DD/MM/YYYY'))
      when b.saldo_dia>0 then
        format('Reaproveita %sh livres do último dia já utilizado e continua sem lacuna nem sobreposição, de %s a %s.',
          b.saldo_dia,to_char(b.periodo_inicio,'DD/MM/YYYY'),to_char(b.periodo_fim,'DD/MM/YYYY'))
      else
        format('O período anterior fechou o dia completo. Esta janela começa no próximo espaço livre e segue sem sobreposição, de %s a %s.',
          to_char(b.periodo_inicio,'DD/MM/YYYY'),to_char(b.periodo_fim,'DD/MM/YYYY'))
    end mensagem
  from base b
  order by b.periodo_inicio,b.certificado_id;
$$;

revoke all on function public.gestor_notificacoes_horas_v36() from public;
grant execute on function public.gestor_notificacoes_horas_v36() to authenticated;

-- 4) Defesa adicional: o cálculo de previsão público da V34.3 continua sendo a
--    fonte da agenda, e o trigger acima impede qualquer inclusão > 200h.

commit;
